version: '3.9'

services:
  db:
    image: postgres:15
    deploy:
      placement:
        constraints:
          - "node.labels.db == true"
    container_name: mgn-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mgn
    networks:
      - mgn-network

  laravel:
    image: jixkgabby/mgn-api:latest
    deploy:
      replicas: 2
    container_name: mgn-app
    restart: always
    tty: true
    volumes:
      - .:/var/www/mgn
    ports:
      - "9001:80"
    networks:
      - mgn-network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: mgn
      DB_USERNAME: user
      DB_PASSWORD: password
      APP_NAME: Radian
      APP_ENV: local
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 9001
      APP_USER: ${APP_USER:-radian}
      APP_GROUP: ${APP_GROUP:-radian}
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: mgn-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7777:80"
    volumes:
      - ./deployment/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/mgn
    depends_on:
      - laravel
    networks:
      - mgn-network

  redis:
    image: redis:alpine
    container_name: mgn-redis
    deploy:
      placement:
        constraints:
          - "node.labels.db == true"
    restart: always
    volumes:
      - ./redisdata:/data
    ports:
      - "6378:6379"
    networks:
      - mgn-network

volumes:
  pgdata:
    driver: local

networks:
  mgn-network:
    driver: overlay # Use overlay for Swarm to enable multi-host networking
