services:
    db:
        image: mysql:8
        container_name: mgn-db
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mgnn
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - mgn-network

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - user=radian
                - uid=1000
        container_name: mgn-app
        restart: always
        tty: true
        volumes:
            - .:/var/www/mgn
        ports:
            - "9001:80"
        networks:
            - mgn-network
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: mgn
            DB_USERNAME: user
            DB_PASSWORD: password
            APP_NAME: Radian
            APP_ENV: local
            REDIS_HOST: redis
            REDIS_PORT: 6379
            PORT: 9001
            APP_USER: ${APP_USER:-radian}
            APP_GROUP: ${APP_GROUP:-radian}
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:alpine
        container_name: mgn-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "7777:80"
        volumes:
            - ./deployment/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/mgn
        depends_on:
            - laravel
        networks:
            - mgn-network

    redis:
        image: redis:alpine
        container_name: mgn-redis
        restart: always
        volumes:
            - ./redisdata:/data
        ports:
            - "6378:6379"
        networks:
            - mgn-network

    worker:
        build:
            context: .
            dockerfile: Dockerfile
            target: worker
            args:
                - user=radian
                - uid=1000
        environment:
            APP_USER: radian
            APP_GROUP: radian
        volumes:
            - .:/var/www/mgn
        networks:
            - mgn-network

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
            target: scheduler
            args:
                - user=radian
                - uid=1000
        environment:
            APP_USER: radian
            APP_GROUP: radian
        volumes:
            - .:/var/www/mgn
        networks:
            - mgn-network

volumes:
    db_data:



networks:
    mgn-network:
        driver: bridge
