services:
    db:
        image: postgres:15
        deploy:
            placement:
                constraints:
                    - "node.labels.db == true"
        container_name: mgn-db
        volumes:
             -  ./docker/postgres/data:/var/lib/postgresql/data
        restart: always
        ports:
            - "${DB_HOST_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: "${DB_USER:-user}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
            POSTGRES_DB: "${DB_DATABASE:-mgn}"
        networks:
            - mgn-network

    laravel:
          image: test_build-api:latest
          container_name: mgn-app
          restart: always
          tty: true
          volumes:
              - .:/var/www/mgn
          ports:
              - "${LARAVEL_PORT:-9001}:80"
          networks:
              - mgn-network

          depends_on:
              - db
              - redis

    nginx:
        image: nginx:alpine
        container_name: mgn-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT:-7777}:80"
        volumes:
            - ./deployment/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/mgn
        depends_on:
            - laravel
        networks:
            - mgn-network

    redis:
        image: redis:alpine
        container_name: mgn-redis
        deploy:
            placement:
                constraints:
                    - "node.labels.db == true"
        restart: always
        volumes:
            - ./docker/redisdata:/data
        ports:
            - "${REDIS_HOST_PORT:-6378}:6379"
        networks:
            - mgn-network

    supervisor:
        image: test_build-worker:latest
        container_name: mgn-supervisor
        restart: always
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
        volumes:
            - .:/var/www/mgn
            - ./deployment/config/supervisor:/etc/supervisor/conf.d
        networks:
            - mgn-network
        depends_on:
            - laravel
            - db
            - redis

volumes:
    db_data:
        driver: local

networks:
    mgn-network:
        driver: bridge
